version: '3'

services:
  postgres:
    image: 'postgres:15.5'
    container_name: 'java-postgres'
    environment:
    - 'POSTGRES_USER=postgres'
    - 'POSTGRES_HOST_AUTH_METHOD=trust'
    - 'POSTGRES_DB=postgres'

  app:
    build: ./
    container_name: 'java-app'
    ports:
    - 8080:8080