name: Java CI

on:
  push:
    branches:
      - master
      - kafka
      - 'feature/*'  # Отслеживать push в ветках feature/*
  pull_request:
    branches:
      - master
      - kafka

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adoptopenjdk'

      - name: Build with Maven
        run: mvn clean package

      - name: Run tests
        run: mvn test